// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mixSQP_rcpp_noapprox
List mixSQP_rcpp_noapprox(const arma::mat& L, const arma::vec& x0, arma::vec w, double convtol, double sparsetol, double eps, int maxiter, int maxqpiter, bool verbose);
RcppExport SEXP _mixSQP_mixSQP_rcpp_noapprox(SEXP LSEXP, SEXP x0SEXP, SEXP wSEXP, SEXP convtolSEXP, SEXP sparsetolSEXP, SEXP epsSEXP, SEXP maxiterSEXP, SEXP maxqpiterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type convtol(convtolSEXP);
    Rcpp::traits::input_parameter< double >::type sparsetol(sparsetolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type maxqpiter(maxqpiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(mixSQP_rcpp_noapprox(L, x0, w, convtol, sparsetol, eps, maxiter, maxqpiter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// mixSQP_rcpp_qr
List mixSQP_rcpp_qr(const arma::mat& Q, const arma::mat& R, const arma::vec& x0, arma::vec w, double convtol, double sparsetol, double eps, int maxiter, int maxqpiter, bool verbose);
RcppExport SEXP _mixSQP_mixSQP_rcpp_qr(SEXP QSEXP, SEXP RSEXP, SEXP x0SEXP, SEXP wSEXP, SEXP convtolSEXP, SEXP sparsetolSEXP, SEXP epsSEXP, SEXP maxiterSEXP, SEXP maxqpiterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type convtol(convtolSEXP);
    Rcpp::traits::input_parameter< double >::type sparsetol(sparsetolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type maxqpiter(maxqpiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(mixSQP_rcpp_qr(Q, R, x0, w, convtol, sparsetol, eps, maxiter, maxqpiter, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixSQP_mixSQP_rcpp_noapprox", (DL_FUNC) &_mixSQP_mixSQP_rcpp_noapprox, 9},
    {"_mixSQP_mixSQP_rcpp_qr", (DL_FUNC) &_mixSQP_mixSQP_rcpp_qr, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixSQP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
