# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mixsqp_rcpp <- function(L, U, V, w, z, x0, usesvd, convtolsqp, convtolactiveset, zerothresholdsolution, zerothresholdsearchdir, suffdecr, stepsizereduce, minstepsize, identitycontribincrease, eps, maxitersqp, maxiteractiveset, verbose) {
    .Call('_mixsqp_mixsqp_rcpp', PACKAGE = 'mixsqp', L, U, V, w, z, x0, usesvd, convtolsqp, convtolactiveset, zerothresholdsolution, zerothresholdsearchdir, suffdecr, stepsizereduce, minstepsize, identitycontribincrease, eps, maxitersqp, maxiteractiveset, verbose)
}

randomized_svd <- function(L, k, oversampling_parameter, power_iteration_parameter, relative_tolerance, sampling_distribution, return_type, rsvd_verbose) {
    .Call('_mixsqp_randomized_svd', PACKAGE = 'mixsqp', L, k, oversampling_parameter, power_iteration_parameter, relative_tolerance, sampling_distribution, return_type, rsvd_verbose)
}

