#' @name tacks
#'
#' @title Beckett & Diaconis tack rolling example.
#'
#' @docType data
#' 
#' @description This data set contains the likelihood matrix and
#' weights for the Beckett-Diaconis tacks example, in which the data
#' are modeled using a binomial mixture. These data were generated by
#' running the "Bmix1" demo from the REBayes package, and saving the
#' arguments passed to \code{KWDual}, as well as the (normalized)
#' solution returned by the \code{KWDual} call.
#'
#' @keywords data
#'
#' @examples
#'
#' # The optimal solution for the tack example is extremely sparse.
#' data(tacks)
#' plot(x,type = "l",col = "royalblue")
#' 
NULL
